---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: clients.caravan.nibious.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: caravan.nibious.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - hostname
                - clientID
                - secretID
                - owner
              properties:
                hostname:
                  type: string
                clientID:
                  type: string
                secretID:
                  type: string
                  format: password
                forwardPorts:
                  type: array
                  items:
                    type: string
                    format: int32
                owner:
                  type: string
                serviceName:
                  type: string
                activePlugins:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Name of the plugin
                      config:
                        x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                connected:
                  type: boolean
                  default: false
                lastContact:
                  type: string
                  format: date-time
      additionalPrinterColumns:
        - name: Owner
          type: string
          jsonPath: .spec.owner
          priority: 1
        - name: Hostname
          type: string
          description: The remote hostname
          jsonPath: .spec.hostname
          priority: 1
        - name: Service
          type: string
          jsonPath: .spec.serviceName
          priority: 1
        - name: Client ID
          type: string
          jsonPath: .spec.clientID
        - name: Connected
          type: boolean
          jsonPath: .status.connected
        - name: Last Ping
          type: date
          jsonPath: .status.lastContact
      
                
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: clients
    # singular name to be used as an alias on the CLI and for display
    singular: client
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Client
