---

apiVersion: v1
kind: Namespace
metadata:
  name: caravan

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: caravan
  labels:
    nibious.com/app: "caravan"
spec:
  replicas: 1
  selector:
    matchLabels:
      nibious.com/app: "caravan"
  template:
    metadata:
      labels:
        nibious.com/app: "caravan"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
      containers:
        - name: server
          image: dev.local/nibious/caravan
          ports:
            - containerPort: 8443
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10001
            capabilities:
              drop: ["ALL"]

---

apiVersion: v1
kind: Service
metadata:
  name: caravan
  namespace: caravan
spec:
  selector:
    nibious.com/app: "caravan"
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 8443

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: caravan
  name: role-caravan
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "update", "patch", "delete"]
  - apiGroups: ["caravan.nibious.com"]
    resources: ["clients", "clients/status"]
    verbs: ["get", "create", "update", "patch", "delete", "list", "watch"]


---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-caravan
  namespace: caravan
subjects:
  - kind: ServiceAccount
    name: default
    namespace: caravan
roleRef:
  kind: Role
  name: role-caravan
  apiGroup: rbac.authorization.k8s.io

---


