apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: nibious-caravan 
build:
  artifacts:
  - image: dev.local/nibious/caravan
    context: ../../
    docker:
      dockerfile: deploy/server/Dockerfile
      cacheFrom:
      # Local Docker builder replaces cache references to the artifact image with
      # the tagged image reference, useful for caching from the previous build.
      - dev.local/nibious/caravan
manifests:
  rawYaml:
    - service.yaml
deploy:
  kubectl: {}
